### PR TITLE
property actions

### PR DESCRIPTION
**Pull request by pvilalta**
hello team,

Here is a new implementation -> actions
It's a property that can be added into steps filled with "actionnable". 
It serves the currentStep which is played in the guided-tour.

The code below (in platform) is directly related to the code in the PR. it will be pushed afterwards

```js
actions: {
   projectViewSetter: projectId => {
      projectView.set(projectId, DEFAULT_PROJECT_VIEW);
   }
}
```

Paul

### CODE REVIEW

**Comment by NicolasRichel** [comment]
This seem to be a nice approach to add some custom actions on a step.
However, it looks like it is actually very specific to the platform...
I think it would be better to find a generic way of registering actions on specific steps that would not depend on the application in which the guided-tour will be used.
Otherwise we will end up with a library that contain many specific parts related different applications.

Here are some ideas :
  - **(1)** the `actions` field (`step.actions`) could be an array (instead of an object) that contain a list of functions to execute when we enter the step.
  - **(2)** the target element of the step could have an attribute `data-guide-param` that define the parameter passed to the actions functions.

Example :
```js
if (step.actions) {
  step.actions.forEach(
    action => action( target.getAttribute("data-guide-param") )
  );
}
```

On the **platform** side it would be used like this :
```js
// tour definition file

steps = [
  ...
  {
    ...
    actions: [
      projectId => projectView.set(projectId, DEFAULT_PROJECT_VIEW)
    ]
  },
  ...
];
```

Maybe it won't be so simple but I think it would be nice to try.

**Review by NicolasRichel — CHANGES_REQUESTED** [review]
See comment in above.

**Comment by pvilalta** [comment]
> This seem to be a nice approach to add some custom actions on a step. However, it looks like it is actually very specific to the platform... I think it would be better to find a generic way of registering actions on specific steps that would not depend on the application in which the guided-tour will be used. Otherwise we will end up with a library that contain many specific parts related different applications.
> 
> Here are some ideas :
> 
> * **(1)** the `actions` field (`step.actions`) could be an array (instead of an object) that contain a list of functions to execute when we enter the step.
> * **(2)** the target element of the step could have an attribute `data-guide-param` that define the parameter passed to the actions functions.
> 
> Example :
> 
> ```js
> if (step.actions) {
>   step.actions.forEach(
>     action => action( target.getAttribute("data-guide-param") )
>   );
> }
> ```
> 
> On the **platform** side it would be used like this :
> 
> ```js
> // tour definition file
> 
> steps = [
>   ...
>   {
>     ...
>     actions: [
>       projectId => projectView.set(projectId, DEFAULT_PROJECT_VIEW)
>     ]
>   },
>   ...
> ];
> ```
> 
> Maybe it won't be so simple but I think it would be nice to try.

here is the new implementation platform-side

```js
  action: () => {
    const projects = document.querySelectorAll(
      "[data-guide=dashboard-project]"
    );

    const projectId = Array.from(projects).find(p => p.dataset.guideClick)
      .dataset.guideParam;

    projectView.set(parseInt(projectId, 10), DEFAULT_PROJECT_VIEW);
  }
```

**Review by NicolasRichel — APPROVED** [review]

**Pull request merged**
